name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.8',  '3.10' ]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install .

      - name: Run flake8 (check docstrings)
        run:
          flake8 ./src
      - name: Run black
        run: |
          black --check ./src
          black --check ./tests
      - name: Run mypy
        run: |
          mypy --ignore-missing-imports ./src
          mypy --ignore-missing-imports ./tests
      - name: Run pytest
        run:
          pytest ./tests
